baseURL = 'https://5moreminutesgaming.com/'
languageCode = 'en-us'
title = '5 More Minutes Gaming'
theme = "hugo-theme-terminal"


[markup]
  defaultMarkdownHandler = 'goldmark'

[params]

[params.author]
    name = "5 More Minutes Gaming"
    email = "five-more-minut-4925@pages.plusgoogle.com"
    twitter = "@allmightyspiff"

[params.podcast]
    description = "5 More Minutes Gaming Podcasts"
    tagline = "5 More Taglines"
    cdn_url = "https://s3.us-east.cloud-object-storage.appdomain.cloud/5moreminutespodcast/"
    download_url = "https://s3.us-east.cloud-object-storage.appdomain.cloud/5moreminutespodcast/"

